# Dockerfile generated by GeneXus (.NET)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
LABEL maintainer="alan_ <alan_@example.com>"
WORKDIR /app
COPY ["temp/", "/app"]
ENTRYPOINT ["dotnet", "bin/GxNetCoreStartup.dll"]
